### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by georgepoulos** [VrushankPatel/Eduwiz#1]
Hello!
Your projects seems very interesting. I try to test it but  I have problem with arc4, (I cannot install it)
Have you any idea about this? and could you create a requirements file?

**Comment by VrushankPatel** [comment]
[arc4 library python.zip](https://github.com/VrushankPatel/Eduwiz/files/3513223/arc4.library.python.zip)
Try this....

**Comment by VrushankPatel** [comment]
> Hello!
> Your projects seems very interesting. I try to test it but I have problem with arc4, (I cannot install it)
> Have you any idea about this? and could you create a requirements file?

[arc4 library python.zip](https://github.com/VrushankPatel/Eduwiz/files/3513225/arc4.library.python.zip)
Try this to install ARC4...
